// Generated by https://quicktype.io

export interface UserFavorites {
    id:             number;
    card:           Card;
    purchaseDate:   string;
    purchaseAmount: number;
    purchaseNumber: string;
}

export interface Card {
    id:        number;
    title:     string;
    posterUrl: string;
}
